title: Semantic Release
description: Semantic Release Learning Hour
theme: just-the-docs

url: https://ibanfr.github.io/semantic-release-kata
repository: https://github.com/ibanFR/semantic-release-kata

aux_links:
  Iv치n Fern치ndez: https://ibanfr.github.io/
  View on GitHub: https://github.com/ibanFR/semantic-release-kata

aux_links_new_tab: true
back_to_top: true
back_to_top_text: "Back to top"

collections:
  explanation:
    output: true
  how-to:
    output: true
  reference:
    output: true

just_the_docs:
  collections:
    explanation:
      name: Explanation
    reference:
      name: Reference
    how-to:
      name: How-To

callouts:
  warning:
    title: Warning
    color: red

defaults:
  # All regular Jekyll pages
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default

  # Explanation collection
  - scope:
      path: ""
      type: "explanation"
    values:
      layout: default

  # How-to collection
  - scope:
      path: ""
      type: "how-to"
    values:
      layout: default

  # Reference collection
  - scope:
      path: ""
      type: "reference"
    values:
      layout: default

# Footer content
# appears at the bottom of every page's main content
# Note: The footer_content option is deprecated and will be removed in a future major release. Please use `_includes/footer_custom.html` for more robust
footer_content: "Iv치n Fern치ndez. All rights reserved."

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/ibanFR/semantic-release-kata" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately
